version: '3'

services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  customer-service:
    build: ./customer-service/
    depends_on:
      - postgres
    ports:
      - 7000:7000
    environment:
      PORT: 7000
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/postgres
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  order-service:
    build: ./order-service/
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/postgres
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  product-service:
    build: ./product-service/
    depends_on:
      - postgres
    ports:
      - 9000:9000
    environment:
      PORT: 9000
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/postgres
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password