spring:
  application:
    name: consumer-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_ENDPOINT:localhost}:5432/postgres
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: update
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:7000}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/ui
  show-actuator: true