spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_ENDPOINT:localhost}:5432/postgres
    username: ${POSTGRES_USERNAME:eventuate}
    password: ${POSTGRES_PASSWORD:eventuate}

server:
  port: ${PORT:8000}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/ui
  show-actuator: true