spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: update
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8000}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/ui
  show-actuator: true